### ISSUE TITLE
synchronization works until the app is restarted

### ISSUE THREAD

**Issue by MarkWieczorek** [flathub/org.kde.kasts#44]
After installing kasts on Fedora linux, and initiating a sync with my nextcloud server, everything worked fine. However, after closing the app and reopening the app, synchronization no longer works:

* When going to the synchronization preference panel, it say "synchronization disabled" under account.
* Clicking on "login" allows you to re-add your password (the account name and server are saved), however, after clicking ok, the window closes, and you are left in the same state as before. No errors are noted in the log.
* If you delete the ` .var/app/org.kde.kasts` directory, and start over, synchronization does work, until you close and re-open the app!

There are several instances of people noticing this same problem on the web (this is just one example: https://www.mail-archive.com/kde-bugs-dist@kde.org/msg667372.html). I am assuming that this is flatpak problem, but it is possible that it is a fundamental issue with the app itself.

**Comment by mogwa1** [comment]
As you mentioned, there have been other reports before.  However, in all the cases that I know of, the issue was actually in the keychain app.  Kasts stores the password in your keychain app through qtkeychain.  Qtkeychain can use several protocols to communicate with various keychain apps (gnome keyring, kwallet, keepassxc etc.).  For flatpaks, it's probably going to be the secret service dbus protocol.  If you've managed to log in the first time, then the keychain app did acknowledge the fact that the password got stored.  If Kasts says that it's logged out on the second run, then that means that it did not manage to retrieve the stored password from the keychain, e.g. because the keychain is locked and/or the retrieval request silently timed out.  So, in that case, Kasts is correctly reporting it's not signed in because it doesn't have the password.

Note that you probably have a keychain running, because if you don't, then Kasts will alert you and prompt for your password and optionally store it on disk instead of the keychain.

So, it's probably a good idea to check your keychain app.

NB: Deleting the `.var/app/org.kde.kasts` directory works because it wipes the username and server url (as well as all of the other app data), which will reset the synchronization status.

**Comment by MarkWieczorek** [comment]
Thanks for the advice. Unfortunately, my problem is exactly the same as in the link I provided above, which is confirmed and appears to still be unresolved. 

I am using a brand new fedora system, and it is not clear how to "check the keychain app" and what I should be looking for. Opening the "passwords and keys" app shows that there is an entry for the kasts app, and that the login keychain is unlocked.

**Comment by mogwa1** [comment]
The link you shared is a partial archive of a bug report on bugs.kde.org (https://bugs.kde.org/show_bug.cgi?id=451836).  I don't know why it's not showing the full contents, but that bug was resolved (by me).

Anyway, everything works fine with respect to password storing and retrieving for me.  That means that the lib calls to qtkeychain are working properly.  So that means that the problem must be due to something in qtkeychain or one of its dependencies.

You could check whether you accidentally are running two keychain managers at the same time.  E.g. most distros automaticallly start gnome-keyring, even on non-gnome DEs.  I don't know which DE you are running, but if it's not gnome it could also have a keyring application which might clash with gnome-keyring.
(Note that this is just one example of what could go wrong.)

**Comment by MarkWieczorek** [comment]
I am not running more than 1 keychain manager. I do have keepassxc installed, but I have not enabled the secret service integration.

I have made some progress on getting this to work, but there still seems to be an issue, most likely with the default settings of the flatpack. First, I enabled all of the "well known sockets" for Kasts using Flatseal (including x11, wayland, fallback-x11, pulseaudio, session-bus, system-bus, ssh-auth, pcsc, cups, and gpg-agent). Next, by repeatedly opening and closing Kasts, I discovered that sometimes it would log in automatically to my account! However, the successful logins occurred only less than half of the time, and in every case, no errors are reported in the app when the login wasn't successful.

I have no idea what could cause this behavior. Perhaps it is some sort of timeout that is set way too short, but I am just guessing.

**Comment by MarkWieczorek** [comment]
I think that I partially solved this problem. In the Fedora app store, there are three versions of Kasts 
* Fedora Linux (registry.fedoraproject.org) : Flatpak
* Fedora Linux (Fedoraproject.org) : RPM
* Fedora flathub selection (dl.flathub.org) : Flatpak

I initially was using the flatpak from registry.fedoraproject.org, not realizing that this version is different from the flathub version. After uninstalling the fedoraproject.org version, and installing the version from flathub.org, the problem went away and I have no problems syncing.

I guess you can close this issue. If you know where to open an issue with registry.fedoraproject.org, let me know.

**Comment by Justinzobel** [comment]
https://bugzilla.redhat.com/ for Fedora flatpak issues. That or
https://pagure.io/fedora-kde/SIG/issues
